name: flutter_training
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ^3.22.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  json_annotation: ^4.9.0
  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training-template.git
      ref: main
      path: packages/yumemi_weather

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  yumemi_lints: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/